import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import InfoBar from "@/components/InfoBar";
import NavBar from "@/components/NavBar";
import FooterSection from "@/components/FooterSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Road Rover by Luca",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/RR-LUCA-black.ico" />
      </head>
      <body className={inter.className}>
        <InfoBar />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
